'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pillers
    Public Property Id As Integer
    Public Property PillerDV As String
    Public Property PillerEN As String
    Public Property PillerDescDV As String
    Public Property PillerDescEN As String
    Public Property PillerNo As Nullable(Of Integer)

    Public Overridable Property Strategies As ICollection(Of Strategy) = New HashSet(Of Strategy)

End Class
