'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class StrategicPlanEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=StrategicPlanEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Schedules() As DbSet(Of Schedule)
    Public Property Sections() As DbSet(Of Section)
    Public Property Status() As DbSet(Of Status)
    Public Property StrategicActions() As DbSet(Of StrategicAction)
    Public Property StrategicActivities() As DbSet(Of StrategicActivity)
    Public Property Strategies() As DbSet(Of Strategy)
    Public Property StrategySections() As DbSet(Of StrategySection)
    Public Property Pillers() As DbSet(Of Pillers)
    Public Property sysdiagrams() As DbSet(Of sysdiagram)

End Class
