'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Schedule
    Public Property Id As Integer
    Public Property StrategicActivityID As Integer
    Public Property Year As Integer
    Public Property Qt_One As Nullable(Of Boolean)
    Public Property Qt_Two As Nullable(Of Boolean)
    Public Property Qt_Three As Nullable(Of Boolean)
    Public Property Qt_Four As Nullable(Of Boolean)

    Public Overridable Property StrategicActivity As StrategicActivity

End Class
