'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Status
    Public Property Id As Integer
    Public Property StrategicActionID As Integer
    Public Property DateTime As Date
    Public Property StatusDV As String
    Public Property StatusEN As String
    Public Property StatusUser As String

    Public Overridable Property StrategicActivity As StrategicActivity

End Class
