'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StrategySection
    Public Property Id As Integer
    Public Property StrategyID As Integer
    Public Property SectionID As Integer

    Public Overridable Property Section As Section
    Public Overridable Property StrategicAction As StrategicAction

End Class
