'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StrategicAction
    Public Property Id As Integer
    Public Property RefCode As String
    Public Property ActionDV As String
    Public Property ActionEN As String
    Public Property StrategyID As Integer

    Public Overridable Property StrategicActivities As ICollection(Of StrategicActivity) = New HashSet(Of StrategicActivity)
    Public Overridable Property Strategy As Strategy
    Public Overridable Property StrategySections As ICollection(Of StrategySection) = New HashSet(Of StrategySection)

End Class
