'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Strategy
    Public Property Id As Integer
    Public Property RefCode As String
    Public Property StrategyDV As String
    Public Property StrategyEN As String
    Public Property Result As String
    Public Property PillerID As Integer

    Public Overridable Property StrategicActions As ICollection(Of StrategicAction) = New HashSet(Of StrategicAction)
    Public Overridable Property Piller As Pillers

End Class
